# Generated by Django 2.2 on 2019-04-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
    ]
